### ISSUE TITLE
Garage Door Status Hangs After Initiating An Open or Close Command in Home App

### ISSUE THREAD

**Issue by designzguy** [nicoduj/homebridge-gogogate2#1]
After installing the plugin and adding the configuration to my config file for Homebridge, the 2 garage doors show up in Homekit. 
When I initiate an "Open" or "Close" command the status shows "Opening" and "Closing" but never finishes or updates to a status change of "Closed" or "Open".
I have verified that the doors have completed their operation of closing and are closed or open via the GoGoGate2 app on my phone. 
For some reason, the check status operation isn't being received after the door is closed or opened.

**Comment by nicoduj** [comment]
Hi !

Thank you for the feedback, I can confirm the issue. I will work on it asap . From what I saw, if I close home app, at some point the "opening" or "closing" status stops and the gate display its correct state when I launch it again. 

Feel free to launch homebridge in debug mode (-D) and give me your logs if you see any thing strange.

**Comment by nicoduj** [comment]
Hi,
have a look at latest version, hope it will work a bit better (still not completely sure it is 100% reliable)

**Comment by designzguy** [comment]
I just tried the updated plugin and it’s working. There is only a 5-6 second delay from when the GoGoGate2 app reports the door has opened/closed compared to when HomeKit reports the door has been opened/closed. This is totally acceptable and I appreciate your hard work in getting this plugin to work.

**Comment by cargueta001** [comment]
![B2172AB9-688A-4744-9AA3-B8312EF0DBEE](https://user-images.githubusercontent.com/48275759/55211140-09a9f680-51a8-11e9-8d61-d77b87a6a0f7.jpeg)

With the latest build, I have noticed that the gate status is hanging/stuck with the Home app but the Gogogate2 App reports the correct status. Any ideas? Thanks in advance.

**Comment by nicoduj** [comment]
@cargueta001  Hi, What is your config file ? I mainly use Siri , but did not notice that. 

Is it only while closing ? 

(Btw can you open a new issue instead of commenting a closed one ? Will help if others have the same problem. Thank you)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
