### ISSUE TITLE
door can switch to closing while opening

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-gogogate2#13]
While opening, door might switch from opening to closing in home app before completion of operation

**Comment by designzguy** [comment]
I can confirm that version 0.1.0 has fixed issue #13 for me. The garage icon now shows the "opening" state until the garage door finishes opening then changes to "open" state.

**Comment by nicoduj** [comment]
reopen since the issue is still there if you close / open the home app after opening the door (it switches to closing), in 1.0
