### ISSUE TITLE
temperature rounding

### ISSUE THREAD

**Issue by joff0** [nicoduj/homebridge-gogogate2#15]
I've just noticed on the temperature that it always seems to be rounded, e.g.:
gogogate value: 6219
Homekit:  6
So I would expect to see 6.2 in homekit.

gogogate value: 7825
Homekit:  8
So I would expect to see 7.8 in homekit.

Ps. many thanks for this plugin, has really simplified my setup!

**Comment by nicoduj** [comment]
Hi, will check since from hap characteristic the precision should indeed be 0.1 ! Thanks for reporting 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Just checked it is home app which does the rounding at 0.5 . Eve app for example respect the 0.1 precision, so can’t do better than I did.
![0b4e592e-5e5d-475c-a846-f1033b7a2b6f](https://user-images.githubusercontent.com/19813688/53127608-2af14480-3563-11e9-9f61-d5096d3cbd15.jpeg)
![67a72b08-a75b-46eb-b360-093bb8d0929f](https://user-images.githubusercontent.com/19813688/53127609-2af14480-3563-11e9-9d1b-84bc00d95183.jpeg)
