### ISSUE TITLE
Gate Status Hangs

### ISSUE THREAD

**Issue by cargueta001** [nicoduj/homebridge-gogogate2#20]
![8AD523A9-6D52-4764-8FD6-E60DB4097EE5](https://user-images.githubusercontent.com/48275759/55212315-8212b680-51ac-11e9-949a-b69a1712b99f.jpeg)

Gate Status hangs occasionally and requires restart of Homebridge to update properly. Gogogate2 App shows correct status constantly.

**Comment by cargueta001** [comment]
![1946CF5E-9009-429E-9AC1-5EC62071C358](https://user-images.githubusercontent.com/48275759/55212368-bab29000-51ac-11e9-9941-038d8cc5c6fd.jpeg)

Here is my config file. This is applicable to both Opening and Closing status. I have altered the time intervals to see if that would help but that has yielded the same results. I will mention also that my gate has a photobeam safety sensor that monitors obstructions. By default my gate circuit board has a auto close to 60 seconds.

**Comment by nicoduj** [comment]
Ok thank you ! Will try to reproduce, if you could post homebridge log in debug mode it would be perfect :) 

Ans by the way : you are operating the gate through home app directly or through some automation and just checking its status ? I suppose if you close the app and reopen it the status is ok then ?

**Comment by cargueta001** [comment]
No, thank you! This plugin is the only reason why I purchased the Gogogate2 to begin with!

I strictly rely on the Home app for access but I resort to the Gogogate2 App when the hanging begins and I need to open/close the gate. I have a Home app location based automation to open the gate when I arrive home and that is a hit or miss for me unfortunately. I tend to force quit the Home App occasionally to see if the status has changed but it does not make a difference.

**Comment by cargueta001** [comment]
![B66A2B0C-43C1-4472-B245-5DA6AA2A8143](https://user-images.githubusercontent.com/48275759/55214654-8773ff00-51b4-11e9-8121-dbfa85a78816.png)
![3549DD46-DAFC-47C8-AA8D-7D131C719B9D](https://user-images.githubusercontent.com/48275759/55214655-8773ff00-51b4-11e9-8e37-d5440a50090a.png)

Here are my debug logs. Hope that helps!

**Comment by nicoduj** [comment]
@cargueta001  Sorry, I misread this on my phone. will check deeper this week end, If I correctly read your log you opened then closed your door (open at 6:43:33 and close at 6:43:46 ? ) It was detected as opened at 6:43:43 and closed at 6:45:06 . So the logic seems ok, and you confirm that it stays in opening or closing way, correct ?


I am also planning to move this plugin to dynamic platform so it doesn’t hang homebridge startup in case of Gogogate reach ability problem.

By the way I use Siri to open / close (with car play) the trick is to have a dummy switch that interacts with the door if you don’t want to Siri to ask you to pick the phone :)

**Comment by nicoduj** [comment]
@cargueta001 can I ask which version you were on previously and that was not having this issue ?

And to be sure, does it always happen or is itonly sometimes ? The log your provide is when you had this problem, or it worked ok this time ?

**Comment by cargueta001** [comment]
Yes, the timer is set to 60 seconds to automatically close the gate on the circuit board of the gate. So, when the gate is opened and let's say I hit the button again in the Home App to stop the process to close the gate is when the status becomes out sync. This also happens randomly for both opening and closing, as if it can't catch up to the commands given. I know that my other tenant is using a physical gate opener and she may be closing the gate before it fully opens as if to prevent the gate from opening all the way for a car. She uses it as a doorway unfortunately.

The last build that appeared to work was 0.1.2 and perhaps 0.1.3. The log I provided previously is when it was not working. I've attached another log from this morning as the issue happened again this morning. I have to reboot Homebridge in order for the hanging to stop.

![4856EF3B-AFA8-4106-BB73-2E211FE0C913](https://user-images.githubusercontent.com/48275759/55244090-b6629300-51fd-11e9-9df9-36f153489b85.png)

**Comment by nicoduj** [comment]
Thank you. There is no command sent in your last log, does that mean that upon homebridge restart you add this issue without operating the gate through HomeKit ?

**Comment by cargueta001** [comment]
When I have this issue, I simply restart Homebridge so that it reflects the proper status. After several hours, around the time people start arriving home is when the issue begins. In the past, I've had a login issue appear in the logs and that required rebooting my raspberry pi in order to resolve the login attempts. As of right now, the status is closed which is accurate based on the Gogogate2 App.

![9447BBE0-5A86-4F2C-B0B3-CA35415A5C32](https://user-images.githubusercontent.com/48275759/55250259-07c54f00-520b-11e9-9ffb-77c2833a6e54.jpeg)
![B2D2D347-5F44-4F0A-8677-E45962B38E44](https://user-images.githubusercontent.com/48275759/55250260-07c54f00-520b-11e9-8ce4-673ee7e13247.jpeg)

I also have the dummy switches setup in my config file to simplify the process in hopes that it would help but unfortunately the same problem occurs.
![C37D27AE-7DC6-4A93-9E73-879C75E8FE9D](https://user-images.githubusercontent.com/48275759/55250347-37745700-520b-11e9-84db-893670785186.jpeg)

**Comment by nicoduj** [comment]
Ok, i am not sur i completely understand your setup, but will try to reproduce . Be aware that in case of power loss of Gogogate and wireless sensor, the status in the app is not good at reboot

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
I tried getting back home and had no issue. What I can do is to put maybe a bit more logs in a new version to narrow your issu, sorry . Will take some time to go through the code / your logs also and see if I have any clue.

**Comment by nicoduj** [comment]
I just think at something, since you have location based actions : is there any chance that the location based tirggers while a manual operationis in progress (because it wasn't triggered while you arrived, but some times latter ?) . Maybe you could try without those location based actions to see if it is the problem ?

**Comment by cargueta001** [comment]
I will go ahead and remove the actions but to my knowledge, they worked in prior versions of the code. The issue began again this morning when people were leaving and the gate had been opened and closed a few times.

Is there a pause state possibility? For example, if  I say "Hey Siri, open gate switch", the gate will open, but if I say immediately after "Hey Siri, close gate" will that cause problems?

**Comment by nicoduj** [comment]
As I said in the readme, I made a lot of refactoring in the latest version (in order to prepare to dynamic platform), so there can be some issue but it is difficult to narrow it since it works. It can definitely be linked to something like 2 commands sent while operation in progress, i will try to test such things but since every setup has its "specificit" sometimes it can be difficult to reproduce without a step by step guide ....

If you don't have time to help me debug this, you can safely go back to previous version, i will perfectly understand !

**Comment by cargueta001** [comment]
I will gladly help debug as you suggested. I'd like to understand the root cause as well.

I have removed the location based automations in the Home app. Like you said, it seems like it's connected to multiple commands while in progress. Would you advise changing anything in my config file?

**Comment by nicoduj** [comment]
Great , it helps narrow the issue . For the moment don’t change anything, I will try to reproduce with multiple commands scenario and keep you informed . By your side if it is stable this way or if you encounter the issue again just tell me so that I don’t follow a dead end :)

Have a nice week end by the way !

Nicolas

**Comment by cargueta001** [comment]
<img width="1920" alt="1" src="https://user-images.githubusercontent.com/48275759/55265138-3b689f00-5234-11e9-927f-e7fd24eccd76.png">
<img width="1920" alt="2" src="https://user-images.githubusercontent.com/48275759/55265139-3b689f00-5234-11e9-970f-4c12ea8c6e2a.png">
<img width="1920" alt="3" src="https://user-images.githubusercontent.com/48275759/55265140-3b689f00-5234-11e9-820b-dcd14831a10a.png">

Here are the latest logs. I altered the automations prior to these logs so they are purely setup by manually selecting the Open Switch.

**Comment by cargueta001** [comment]
It continues to show "Closing" and repeats the last log.

**Comment by nicoduj** [comment]
in your last log the status got from gogogate is strange, you got a "." and not a FAIL (closed) or  OK (open).

**Comment by nicoduj** [comment]
and I don't see any wireless sensor logs, are you using a wired sensor ?

**Comment by nicoduj** [comment]
and I see you've got 2 switches activated (arrived home / opengate), are they not both triggering something on the gate ?

**Comment by nicoduj** [comment]
@cargueta001  I just saw your config and think there is a mistake in it : you must not add the trailing s in timers.
Should be something like this : 
            "refreshTimer" : 30,
            "maxWaitTimeForOperation" : 45,
"refreshTimerDuringOperation": 5

not sure it is an issue but still it can explain the non ending loop on timeout in your log.

**Comment by cargueta001** [comment]
Yes, I am using a Wired Sensor. The second switch is to deactivate the alarm security system.

The "Scene" is able to activate the "Arrived Home" but the "Open Gate" results in a hanging status.

I will adjust the config file and monitor the actions. Thank you for your persistence Nicolas 👍🏻

**Comment by nicoduj** [comment]
I have no experience with the wired sensor, might be a 2 things thing :) : wired sensor might no send an ok , and since your timer is not set properly i hang without detecting the end operation and not having the timeout work properly. I was maybe less strict on the status check in older version .


Nicolas

**Comment by cargueta001** [comment]
![91F8DC0E-EBB7-4D28-B135-6B9E1DF82D6A](https://user-images.githubusercontent.com/48275759/55273168-f6b92400-5284-11e9-8a7b-0625e25455a3.png)
![F7A6B4E9-74D0-409D-92FC-5FD8874C2611](https://user-images.githubusercontent.com/48275759/55273169-00428c00-5285-11e9-9bde-41ccbed0d8ad.png)

This is now with the adjusted config file. And without any trigger, I'm still receiving an endless loop.

**Comment by nicoduj** [comment]
yes, but this one is normal (refresh every 30s)
 and the status is ok this time. Can you trigger ?

**Comment by nicoduj** [comment]
I am publishing a new version, I made some changes around your issue, let me know after update if you still have the issue. There is a bit more log also so that I can have more information if the issue persists

@cargueta001 : the update is available

**Comment by cargueta001** [comment]
Thank you Nicolas. I have updated and will test the build shortly.

Here are my latest logs:
![35A20DEE-C0E6-494B-B3EB-ED231C805C36](https://user-images.githubusercontent.com/48275759/55278387-df9c2580-52c8-11e9-8fec-0efe371ad687.png)

**Comment by nicoduj** [comment]
Ok, let me know if it is fixed, or not !


Nicolas

**Comment by nicoduj** [comment]
@cargueta001 Hi, how is testing going on ?

**Comment by cargueta001** [comment]
Hi Nicolas, THANK YOU THANK YOU THANK YOU!

I did some extensive usage on the plugin this weekend and also had my wife report no problem within the Home app. I meant to write back yesterday with an update, however, I wanted to see the usage this morning as well. Everything updates accordingly and I haven't had the need to restart Homebridge!

Were the changes to the code substantial? I'm really looking forward to the new beta plugin but will patiently wait as I just got this one working successfully. Thank you once again.

**Comment by nicoduj** [comment]
>Hi Nicolas, THANK YOU THANK YOU THANK YOU! ...

@cargueta001 great ! Happy to have solved this one :) Enjoy, I will test the beta myself but not planning to release it until I have linked my second door (not so many users on this plugin so feedback will be more difficult to have I guess)
And no, changes were not so important just a problem I think in some case of disconnection by the Gogogate and error handling mainly. But as always, finding the bug takes far more time than fixing it :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
