### ISSUE TITLE
update to beta fails

### ISSUE THREAD

**Issue by joff0** [nicoduj/homebridge-gogogate2#22]
Hi Nicolas,

I just wanted to check your beta, however the update on my Synology Docker instance fails with following message:

/homebridge # npm install -g homebridge-gogogate2@beta
npm ERR! code ETARGET
npm ERR! notarget No matching version found for homebridge-gogogate2@beta
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

Am I doing something wrong, I've started Terminal via homebridge-config-ui-x v4.0.2 in Chrome Browser.

I've noticed that in the npm registry no beta tag is available: https://registry.npmjs.org/homebridge-gogogate2

Cheers,
Joff

**Comment by nicoduj** [comment]
Hi,

it is not yet published :) I do not have much time right now, I will publish it if you want but not fully tested !

**Comment by nicoduj** [comment]
It is published !
