### ISSUE TITLE
Working under HAP-NodeJS?

### ISSUE THREAD

**Issue by Bedzaa-zz** [nicoduj/homebridge-gogogate2#25]
Hi nicoduj, thank for your work on that! Is Your release working under HAP-NodeJS environment or under homebridge only? I run all my homekit incompatible devices under HAP-NodeJS and it would be so great to add GogoGate2 to my homekit...

I wish You can help  me

Cheers
Bedzaa

**Comment by nicoduj** [comment]
Hi, sorry for my late answer, I missed your post. I am only working on homebrudge for the moment, sorry !
