### ISSUE TITLE
Ability to inform which user has opened the door

### ISSUE THREAD

**Issue by MIGI10** [nicoduj/homebridge-gogogate2#27]
I know it's very complicated for it to inform which user has done the action with notifications but it would be nice if there was a way. Instead of having Homekit push notifications saying "Front Gate has been opened" it would be cool if it said "Front Gate has been opened by John" (using users created in Gogogate2). Surely it can't be easily accomplished by limits imposed by HomeKit but I wanted to share my idea.

**Comment by nicoduj** [comment]
Hi,
I agree, would be nice but don't see anyway to do this through homebridge / homekit. I think you must rely on gogogate app notification for that.
