### ISSUE TITLE
temperature bug

### ISSUE THREAD

**Issue by toshibochan** [nicoduj/homebridge-gogogate2#47]
<img width="513" alt="Screen Shot 2021-02-11 at 6 49 48 PM" src="https://user-images.githubusercontent.com/15816913/107725157-6f1f0780-6c9a-11eb-9bdf-b270ef1d2bcd.png">
my garage temperature showing -50C but here now is 12C

**Comment by nicoduj** [comment]
Hi, what do you have in gogogate app / website ? Are you on the latest version of the plugin ?

**Comment by toshibochan** [comment]
It show Firmware version 2.70

But I don’t see temperature on the app or web.

**Comment by nicoduj** [comment]
Here on the left. Are you sure you have a working wireless sensor ? 
![Capture d’écran 2021-02-13 à 09 16 17](https://user-images.githubusercontent.com/19813688/107845507-35eeb080-6ddc-11eb-906d-eed8e93b54fd.png)

**Comment by nicoduj** [comment]
Nonews on that, closing. Feel free to reopen if you can confirm you see temperature in gogogate app.
